### PR TITLE
Add AWS KMS asymmetric keys support

### PR DESCRIPTION
**Pull request by cousine**
* Update aws-go to version 1.33.1
* Add AWS KMS Asymmetric Key Support
* Update README

Addresses #684

### CODE REVIEW

**Comment by autrilla** [comment]
AFAICT (please correct me if I'm wrong) this lets folks use some key types they otherwise wouldn't be able to use with SOPS, but it doesn't add full asymmetric key support, right? If I were to export the pubkey from AWS and give it to someone, how could they create a SOPS file and send it to me?

**Comment by cousine** [comment]
@autrilla you are correct this doesn't add full asymmetric key support, it will only allow SOPS to use the asymmetric key type for AWS KMS

**Comment by cousine** [comment]
I'm curious though if there was any design thought regarding full asymmetric support, would love to take a stab at it

**Comment by cousine** [comment]
Just thinking out loud, but one way full asymmetric support in the way you described is to provide the public key and the key resource (in the case of AWS the ARN) of the key, the arn would then be used for metadata, while the public key is used for encryption.

Looking at SOPS architecture, I can see that happen in two places, either we create another keysource that implements the encrypt function but composes other keysources for decryption depending on the decryption source provided, or we implement the public key encryption in the base package while building the tree.

Another question would rise though, and I can imagine this is a more common use case, if someone wants to add a secret to an already encrypted sops file, and they only have a public key, how can they do that? is there a way where the meta can be recalculated? maybe layering the encryption while keeping the structure of the store? WDYT?

**Comment by roshan1988** [comment]
Will this fix me merged anytime in the roadmap ? Is there any workaround for using asymmetric keys from kms in sops ?

**Pull request closed without merging**
