### PR TITLE
azkv: update Azure identity SDK

### PR DESCRIPTION
**Pull request by yann-soubeyrand**
Latest version of the SDK supports Workload Identity Federation on Kubernetes.

### CODE REVIEW

**Comment by hiddeco** [comment]
Duplicate of #1092, which will be updated as soon as the transfer to a CNCF Sandbox project has been completed.

**Comment by yann-soubeyrand** [comment]
Sorry, I didn’t see this PR, however it doesn’t update azidentity to version 1.3.0 which is the one adding support for Workload Identity Federation on Kubernetes if I understood correctly.

**Comment by hiddeco** [comment]
It will be updated to include this as soon as we are in a position in which we can push out releases again. See https://github.com/mozilla/sops/discussions/927#discussioncomment-5728649 for more information around this.

**Comment by hiddeco** [comment]
Closing this as #1092 should be in soon.

**Pull request closed without merging**
