### PR TITLE
Update repository URL from mozilla/sops to getsops/sops

### PR DESCRIPTION
**Pull request by tuxiqae**

### CODE REVIEW

**Review by devstein — COMMENTED** [review]
Hi @tuxiqae thanks for making a PR to fix this! There is already an open PR for this renaming migration, https://github.com/getsops/sops/pull/1247 , so I'm going to close this.

**Comment by tuxiqae** [comment]
The PR in question does not take care of the same issue.
PR #1247 renames the module name, PR #1254 (this one) renames the name of the repo itself.
It might be smarter to add my commit to PR #1247, but that's up to you, I do not think that those two things should depend on one another.

**Comment by devstein** [comment]
@tuxiqae Thank you for clarifying 😅

**Comment by felixfontein** [comment]
Isn't this already covered by #1244?

**Pull request closed without merging**
